"""
Exercise3 Link : 
https://plonk.zksecurity.xyz/1_Getting_started/4_Selectors_and_Interpolation.html
"""


# This file was *autogenerated* from the file exercise3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 = Integer(21888242871839275222246405745257275088548364400416034343698204186575808495617); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_9 = Integer(9)
def interpolate(I, Y):
    """
    Given two lists I and Y of the same length n:
      I = [x1, x2, ..., x_n]
      Y = [y1, y2, ..., y_n]
    where all x_i are distinct, return the Lagrange interpolation polynomial f(x)
    such that f(x_i) = y_i for each i.
    """    
    # Implement Lagrange interpolation formula following PLONK tutorial
    # f(x) = sum_j(y_j * product_i((x - x_i)/(x_j - x_i))) for i != j
    n = len(I)
    f = _sage_const_0 
    
    for j in range(n):
        # Compute Lagrange basis function for j-th point
        L_j = _sage_const_1 
        for i in range(n):
            if i != j:
                L_j *= (x - I[i]) / (I[j] - I[i])
        
        # Accumulate to interpolation polynomial
        f += Y[j] * L_j
    
    return f

p = _sage_const_21888242871839275222246405745257275088548364400416034343698204186575808495617 
F = GF(p)
R = PolynomialRing(F, 'x', names=('x',)); (x,) = R._first_ngens(1)


SL= {_sage_const_1 :_sage_const_1 ,_sage_const_2 :_sage_const_1 ,_sage_const_3 :_sage_const_1 ,_sage_const_4 :_sage_const_0 } #Similar as before, we use dictionaries to map 1..4 to selectors for each gate
SR= {_sage_const_1 :_sage_const_1 ,_sage_const_2 :_sage_const_1 ,_sage_const_3 :_sage_const_1 ,_sage_const_4 :_sage_const_0 }  # Choose the right selector as the same of SL too
SM = {_sage_const_1 :_sage_const_0 ,_sage_const_2 :_sage_const_0 ,_sage_const_3 :_sage_const_0 ,_sage_const_4 :_sage_const_1 }  # Multiplication selector, only gate 4 is a multiplication gate

# Define index list I first
I = [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_4 ]

qL = interpolate(I,list(SL.values())) # Interpolation polynomial for left input selector
qR = interpolate(I,list(SR.values())) # Interpolation polynomial for right input selector
qM = interpolate(I,list(SM.values())) # Interpolation polynomial for multiplication selector

# Variable definitions from previous exercises
a = {_sage_const_1 :_sage_const_0 ,_sage_const_2 :_sage_const_1 ,_sage_const_3 :_sage_const_1 ,_sage_const_4 :_sage_const_3 }  # Left input values
b = {_sage_const_1 :_sage_const_1 ,_sage_const_2 :_sage_const_1 ,_sage_const_3 :_sage_const_2 ,_sage_const_4 :_sage_const_3 }  # Right input values
c = {_sage_const_1 :_sage_const_1 ,_sage_const_2 :_sage_const_2 ,_sage_const_3 :_sage_const_3 ,_sage_const_4 :_sage_const_9 }  # Output values

