

# This file was *autogenerated* from the file test_exercise4.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2)# Test script for exercise4.sage
load('exercise4.sage')

print("=== Exercise 4 Results ===")
print("\nVanishing polynomial Z(x):")
show("Z =", Z)

print("\nQuotient polynomial Q(x):")
show("Q =", Q)

print("\nVanishing polynomial Z1(x) for I' = {1,2}:")
show("Z1 =", Z1)

print("\nQuotient polynomial Q1(x):")
show("Q1 =", Q1)

print("\nQuotient polynomial Q2(x):")
show("Q2 =", Q2)

print("\n=== Verification ===")
print("Is t(x) = Q(x) * Z(x)?", t == Q*Z)
print("Is f1(x) = Q1(x) * Z1(x)?", f1 == Q1*Z1)
print("Is f2(x) = Q2(x) * Z1(x)?", f2 == Q2*Z1)

print("\n=== Constraint polynomial t(x) values at I ===")
for i in I:
    print(f"t({i}) = {t(i)}")

print("\n=== Recursive constraint polynomials values at I' = {1,2} ===")
for i in [_sage_const_1 ,_sage_const_2 ]:
    print(f"f1({i}) = {f1(i)}")
    print(f"f2({i}) = {f2(i)}")

